name: 'Styled Random Quote'
description: 'Automatically generates random quotes on issues/pull requests by provided parameters'
author: 'AlexRogalskiy'

inputs:
  sourceData:
    description: 'JSON data source with action parameters'
    required: false
  requestId:
    description: "Request identifier"
    required: false
  theme:
    description: "Quote image theme"
    required: false
  layout:
    description: "Quote image layout"
    required: false
  GITHUB_TOKEN:
    description: "Github action token"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'image'
  color: 'yellow'
